### ISSUE TITLE
Simple WebServer thread panicked..

### ISSUE THREAD

**Issue by friendbear** [friendbear/oreilly-rust#1]
```sh
❯ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/iron-gcd`
Serving on http://localhost:3000...
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:83:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:83:17

```

**Comment by friendbear** [comment]
fixd #2 

closed #1
